export {
  clearUnavailableAiOptionNotices,
  createGroup,
  deleteGroup,
  getAiOptionCatalog,
  getAuthStatus,
  getDesktopBootstrapSnapshot,
  getDesktopConfig,
  getDesktopRuntimeSnapshot,
  getAiOptionSelection,
  getLocalProxyStatus,
  listGroups,
  logout,
  openErrorLogWindow,
  openGroupManagementWindow,
  openLoginUrl,
  openStatusReportWindow,
  refreshAiOptionCatalog,
  renameGroup,
  resizeMainWindowToContent,
  saveAiOptionSelection,
  showMainWindowWhenReady,
  startLocalProxy,
  stopLocalProxy,
  type AiOptionCatalogSnapshot,
  type AiOptionSelectionSnapshot,
  type AuthStatusSnapshot,
  type DesktopConfigSnapshot,
  type DesktopGroupConfig,
  type DesktopGroupSummary,
  type DesktopRuntimeSnapshot,
  type LocalProxyStatus,
  type PublicAiOption,
  type UnavailableAiOptionNotice
} from "./local-proxy";
